import os, sys
OUT = sys.argv[1] if len(sys.argv) > 1 else '.'
import random
p = 2**255 - 19
def inv(x): return pow(x, p-2, p)

random.seed(20260930)
N = 300
edge = [0, 1, 2, p-1, p-2, (1<<255)-1, (1<<256)-1, p, p+1, p+19, 19, 38]
vals = list(edge)
for _ in range(N):
    vals.append(random.randrange(0, 1 << 256))

pairs = []
for i in range(0, len(vals) - 1, 2):
    pairs.append((vals[i], vals[i + 1]))
if len(vals) % 2 == 1:
    pairs.append((vals[-1], vals[0]))

def tobytes(n):
    return (n % (1 << 256)).to_bytes(32, 'little')

def bytes_lit(b):
    return "[" + ", ".join(str(x) for x in b) + "]"

src = []
src.append("// GENERATED by gen_field_test.py -- do not hand-edit.")
src.append("// Differential test of field25519 against Python's exact bigint")
src.append("// modular arithmetic mod 2^255-19, over random and boundary inputs")
src.append("// (several >= p, to exercise from_bytes/to_bytes' non-canonical")
src.append("// reduction, which RFC 7748 explicitly requires accepting).")
src.append("import field25519;")
src.append("")

want = []

for idx, (a, b) in enumerate(pairs):
    ab = tobytes(a)
    bb = tobytes(b)
    src.append(f"bytes a{idx} = {bytes_lit(ab)};")
    src.append(f"bytes b{idx} = {bytes_lit(bb)};")
    src.append(f"Array<int> fa{idx} = field25519.from_bytes(a{idx});")
    src.append(f"Array<int> fb{idx} = field25519.from_bytes(b{idx});")
    src.append(f'print("add{idx} " + field25519.to_bytes(field25519.add(fa{idx}, fb{idx})).hex());')
    src.append(f'print("sub{idx} " + field25519.to_bytes(field25519.sub(fa{idx}, fb{idx})).hex());')
    src.append(f'print("mul{idx} " + field25519.to_bytes(field25519.mul(fa{idx}, fb{idx})).hex());')
    src.append(f'print("sq{idx} " + field25519.to_bytes(field25519.sq(fa{idx})).hex());')
    src.append(f'print("neg{idx} " + field25519.to_bytes(field25519.neg(fa{idx})).hex());')
    src.append(f'print("fromto{idx} " + field25519.to_bytes(fa{idx}).hex());')

    am = a % p
    bm = b % p
    want.append(f"add{idx} " + ((am + bm) % p).to_bytes(32, 'little').hex())
    want.append(f"sub{idx} " + ((am - bm) % p).to_bytes(32, 'little').hex())
    want.append(f"mul{idx} " + ((am * bm) % p).to_bytes(32, 'little').hex())
    want.append(f"sq{idx} " + ((am * am) % p).to_bytes(32, 'little').hex())
    want.append(f"neg{idx} " + ((-am) % p).to_bytes(32, 'little').hex())
    want.append(f"fromto{idx} " + am.to_bytes(32, 'little').hex())

# inversion + sqrt-helper on a smaller subset (nonzero), since these loop 250+ times each
inv_vals = [v for v in vals if v % p != 0][:60]
for idx, a in enumerate(inv_vals):
    ab = tobytes(a)
    src.append(f"bytes ia{idx} = {bytes_lit(ab)};")
    src.append(f"Array<int> ifa{idx} = field25519.from_bytes(ia{idx});")
    src.append(f'print("inv{idx} " + field25519.to_bytes(field25519.invert(ifa{idx})).hex());')
    src.append(f'print("p58_{idx} " + field25519.to_bytes(field25519.pow_p_minus_5_over_8(ifa{idx})).hex());')
    am = a % p
    want.append(f"inv{idx} " + pow(am, p - 2, p).to_bytes(32, 'little').hex())
    want.append(f"p58_{idx} " + pow(am, (p - 5) // 8, p).to_bytes(32, 'little').hex())

open(os.path.join(OUT, "t_field25519.m31"), "w").write("\n".join(src) + "\n")
open(os.path.join(OUT, "t_field25519.want"), "w").write("\n".join(want) + "\n")
print("wrote", len(src), "src lines,", len(want), "want lines")
