//! C backend.
//!
//! Consumes post-refcount IR and emits a single translation unit. It does no
//! reasoning about ownership -- every rc_inc and rc_dec it emits was already
//! placed by the lowering pass (docs/ir-v0.md §4).
//!
//! The runtime is linked separately and is NOT included here beyond its
//! header; see docs/ir-v0.md §7.1 for why that separation is load-bearing.

use std::fmt::Write;

use crate::ir::{ArithOp, Inst, IrTy, Module, Term, TypeDef, Value};

pub fn emit(m: &Module) -> String {
    let mut o = String::new();

    o.push_str("/* Generated by langc. Do not edit. */\n");
    o.push_str("#include \"rt.h\"\n#include <stdint.h>\n#include <stdlib.h>\n\n");

    // One C struct per user type. Every object starts with the Obj header, so
    // a `ref` is always an `Obj *` and the field access casts.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface {
            writeln!(
                o,
                "/* interface {} -- no layout; values are Obj * */",
                t.name
            )
            .unwrap();
            continue;
        }
        writeln!(o, "/* {} */", t.name).unwrap();
        writeln!(o, "typedef struct {{").unwrap();
        writeln!(o, "    Obj hdr;").unwrap();
        if t.is_enum {
            // A tag and as many machine-word slots as the widest variant
            // needs. The slots are shared between variants, so their C type
            // cannot depend on which variant it is; a reference rides as its
            // pointer, the same way a collection's elements do.
            writeln!(o, "    int64_t tag;").unwrap();
            for k in 0..t.payload_slots() {
                writeln!(o, "    int64_t p{k};").unwrap();
            }
        }
        for (fname, fty) in &t.fields {
            let c = fty.c_name();
            let sep = if c.ends_with('*') { "" } else { " " };
            let fname = c_ident(fname);
            writeln!(o, "    {c}{sep}f_{fname};").unwrap();
        }
        writeln!(o, "}} T{i};").unwrap();
    }
    if !m.types.is_empty() {
        o.push('\n');
    }

    // Function prototypes before the drop functions, which call a type's
    // destructor, and before the TypeInfos, whose vtables name methods.
    if !m.types.is_empty() {
        for f in &m.funcs {
            writeln!(o, "{};", signature(f)).unwrap();
        }
        o.push('\n');
    }

    // A drop function only exists for types that hold references or declare
    // a destructor; rc_dec checks for NULL, so types with neither pay a
    // branch instead of a call.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct || !t.has_drop_fn() {
            continue;
        }
        writeln!(o, "static void drop_T{i}(Obj *o) {{").unwrap();
        if let Some(d) = &t.destructor {
            // The destructor runs FIRST, on a whole object: every field is
            // still alive, so it can use them -- close a descriptor, flush a
            // buffer -- and a field's own destructor runs only afterwards,
            // when the field is released below.
            //
            // The count is 0 here. The destructor borrows `this` like any
            // method, and its body may retain and release it (a local, an
            // argument); at 0 that pair would reach zero a second time and
            // free the object inside its own destructor. So it runs at 1 --
            // the borrow it is given -- and must leave it at exactly 1. More
            // means `this` was stored somewhere that outlives the call: a
            // dead object brought back, whose memory is about to be freed
            // under whoever holds it. That is a bug with no safe
            // continuation, so it traps (docs/destructors-decision.md).
            writeln!(o, "    o->rc = 1;").unwrap();
            writeln!(o, "    {}(o);", c_name(d)).unwrap();
            writeln!(
                o,
                "    if (o->rc != 1) rt_trap(\"object resurrected in its destructor: \
                 `drop` stored `this` somewhere that outlives it\");"
            )
            .unwrap();
            writeln!(o, "    o->rc = 0;").unwrap();
        }
        if !t.needs_drop() {
            writeln!(o, "}}").unwrap();
            continue;
        }
        writeln!(o, "    T{i} *p = (T{i} *)o;").unwrap();
        if t.is_enum {
            emit_enum_slot_switch(&mut o, t, "rc_dec((Obj *)(intptr_t)p->p{k});");
        }
        for (fname, fty) in &t.fields {
            if *fty == IrTy::Ref {
                let fname = c_ident(fname);
                writeln!(o, "    rc_dec(p->f_{fname});").unwrap();
            }
        }
        writeln!(o, "}}").unwrap();
    }
    if m.types.iter().any(TypeDef::has_drop_fn) {
        o.push('\n');
    }

    // A walk function reports the references an object holds, without
    // releasing them. rt_check_unique uses it to decide whether the whole
    // graph reachable from a value crossing a thread boundary is reachable
    // from anywhere else -- see runtime/rt.c. Same condition as the drop
    // function: a type with no reference fields needs neither.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct || !t.needs_drop() {
            continue;
        }
        writeln!(
            o,
            "static void walk_T{i}(Obj *o, VisitFn visit, void *ctx) {{"
        )
        .unwrap();
        writeln!(o, "    T{i} *p = (T{i} *)o;").unwrap();
        if t.is_enum {
            emit_enum_slot_switch(&mut o, t, "visit(ctx, (Obj *)(intptr_t)p->p{k});");
        }
        for (fname, fty) in &t.fields {
            if *fty == IrTy::Ref {
                let fname = c_ident(fname);
                writeln!(o, "    visit(ctx, p->f_{fname});").unwrap();
            }
        }
        writeln!(o, "}}").unwrap();
    }
    if m.types.iter().any(TypeDef::needs_drop) {
        o.push('\n');
    }

    // A copy function per concrete type, for a `const` binding that has to
    // snapshot a shared value (runtime/rt.c, rt_snapshot). Every type gets
    // one, reference fields or not: the runtime does not know a user type's
    // size, so even a struct of ints is copied here. The body is a struct
    // assignment -- the scalars -- then a fresh count, registration with the
    // runtime BEFORE any child is copied (so a cycle closes onto this copy),
    // and each reference replaced by its child's copy.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct {
            continue;
        }
        writeln!(o, "static Obj *copy_T{i}(Obj *o, void *ctx) {{").unwrap();
        writeln!(o, "    T{i} *p = (T{i} *)o;").unwrap();
        writeln!(
            o,
            "    T{i} *n = (T{i} *)rt_alloc(sizeof(T{i}), p->hdr.ty);"
        )
        .unwrap();
        writeln!(o, "    Obj hdr = n->hdr;").unwrap();
        writeln!(o, "    *n = *p;").unwrap();
        writeln!(o, "    n->hdr = hdr;").unwrap();
        writeln!(o, "    rt_copy_register(ctx, o, (Obj *)n);").unwrap();
        if t.is_enum {
            emit_enum_slot_switch(
                &mut o,
                t,
                "n->p{k} = (int64_t)(intptr_t)rt_copy_child(ctx, (Obj *)(intptr_t)p->p{k});",
            );
        }
        for (fname, fty) in &t.fields {
            if *fty == IrTy::Ref {
                let fname = c_ident(fname);
                writeln!(o, "    n->f_{fname} = rt_copy_child(ctx, p->f_{fname});").unwrap();
            }
        }
        writeln!(o, "    return (Obj *)n;").unwrap();
        writeln!(o, "}}").unwrap();
    }

    // One TypeInfo per concrete type: its drop function and its vtable. The
    // vtable has one slot per distinct interface method name in the program,
    // so a dispatch index is a compile-time constant.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct {
            continue;
        }
        let drop = if t.has_drop_fn() {
            format!("drop_T{i}")
        } else {
            "NULL".to_string()
        };
        let walk = if t.needs_drop() {
            format!("walk_T{i}")
        } else {
            "NULL".to_string()
        };
        if m.iface_slots.is_empty() {
            writeln!(
                o,
                "static const TypeInfo ti_T{i} __attribute__((unused)) = \
                 {{ {drop}, NULL, {walk}, copy_T{i} }};"
            )
            .unwrap();
        } else {
            let entries: Vec<String> = t
                .vtable
                .iter()
                .map(|e| match e {
                    Some(fname) => format!("(AnyFn){}", c_name(fname)),
                    None => "NULL".to_string(),
                })
                .collect();
            writeln!(
                o,
                "static const AnyFn vt_T{i}[] __attribute__((unused)) = {{ {} }};",
                entries.join(", ")
            )
            .unwrap();
            writeln!(
                o,
                "static const TypeInfo ti_T{i} __attribute__((unused)) = \
                 {{ {drop}, vt_T{i}, {walk}, copy_T{i} }};"
            )
            .unwrap();
        }
    }
    if !m
        .types
        .iter()
        .all(|t| t.is_interface || t.is_chan || t.is_distinct)
    {
        o.push('\n');
    }

    // String literals are immortal: static storage, RC_IMMORTAL, never freed.
    for (i, s) in m.strings.iter().enumerate() {
        let bytes = s.as_bytes();
        writeln!(
            o,
            "static Str str{i} = {{ {{ RC_IMMORTAL, &rt_str_type }}, {}, {} }};",
            bytes.len(),
            c_string_literal(bytes)
        )
        .unwrap();
    }
    if !m.strings.is_empty() {
        o.push('\n');
    }

    emit_statics(&mut o, m);

    // Escaping `$` could collide two distinct IR names, and a collision here
    // is a silent miscompile. `lower` rejects it with a proper diagnostic
    // before we get this far -- see `check_c_name_collisions` -- so reaching
    // this assertion means that check has a hole, not that the user did
    // something wrong.
    {
        let mut seen = std::collections::BTreeSet::new();
        for f in &m.funcs {
            assert!(
                seen.insert(c_name(&f.name)),
                "two functions map to the same C name: {} \
                 (lower::check_c_name_collisions should have caught this)",
                c_name(&f.name)
            );
        }
    }

    // Prototypes first, so definition order does not constrain call order.
    for f in &m.funcs {
        writeln!(o, "{};", signature(f)).unwrap();
    }
    o.push('\n');

    // One argument struct and one trampoline per spawned function. pthreads
    // takes a single void*, so the arguments are packed on the heap and the
    // trampoline unpacks them.
    let mut spawned: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for f in &m.funcs {
        for b in &f.blocks {
            for i in &b.insts {
                if let Inst::Spawn { func, .. } = i {
                    spawned.insert(func.as_str());
                }
            }
        }
    }
    for name in &spawned {
        let target = m
            .funcs
            .iter()
            .find(|f| f.name == **name)
            .expect("spawned function must exist");
        let cn = c_name(name);
        writeln!(o, "typedef struct {{").unwrap();
        for (i, p) in target.params.iter().enumerate() {
            let t = target.ty_of(*p).c_name();
            let sep = if t.ends_with('*') { "" } else { " " };
            writeln!(o, "    {t}{sep}a{i};").unwrap();
        }
        if target.params.is_empty() {
            writeln!(o, "    int unused;").unwrap();
        }
        writeln!(o, "}} spawn_{cn};").unwrap();
        writeln!(o, "static void *trampoline_{cn}(void *p) {{").unwrap();
        writeln!(o, "    spawn_{cn} *a = (spawn_{cn} *)p;").unwrap();
        let passed: Vec<String> = (0..target.params.len())
            .map(|i| format!("a->a{i}"))
            .collect();
        writeln!(o, "    {cn}({});", passed.join(", ")).unwrap();
        // The spawning side handed this thread a reference per argument --
        // moved if it owned one, retained if it only borrowed. Parameters are
        // borrowed inside the callee (docs/ir-v0.md §5.1), so nobody there
        // will release them: the trampoline is where the transfer ends.
        for (i, p) in target.params.iter().enumerate() {
            if target.ty_of(*p) == IrTy::Ref {
                writeln!(o, "    rc_dec(a->a{i});").unwrap();
            }
        }
        writeln!(o, "    free(a);").unwrap();
        writeln!(o, "    return NULL;").unwrap();
        writeln!(o, "}}").unwrap();
    }
    if !spawned.is_empty() {
        o.push('\n');
    }

    for f in &m.funcs {
        emit_func(&mut o, f, &m.types);
        o.push('\n');
    }

    // rt_wait_all joins every spawned thread. Without it a spawn can
    // outlive the program: its output is lost, and the refcount invariant
    // is reported by atexit while threads are still running.
    //
    // argc/argv are handed to the runtime and nothing else: the program has
    // no parameters, and `os.args()` asks the runtime for them.
    writeln!(
        o,
        "int main(int argc, char **argv) {{
    rt_args_init(argc, argv);
    {}();
    rt_wait_all();
    return 0;
}}",
        c_name("$main")
    )
    .unwrap();
    o
}

/// Module constants' collections, as static data -- docs/reference.md §4.4.
///
/// Each is laid out exactly as the runtime lays out the same collection
/// built at run time, with a count of RC_IMMORTAL, so every read path is the
/// ordinary one and no initialisation code runs: there is no order in which
/// constants come into existence, because they all exist before `main`.
///
/// `static const`, so they land in read-only memory: a write the runtime's
/// trap somehow missed faults instead of corrupting a table every thread
/// reads. `__attribute__((unused))` because a constant nobody reads is still
/// checked and still emitted, and gcc warns about an unused static const in
/// C.
///
/// An array is its own anonymous struct with the element count spelled out,
/// rather than the runtime's `Arr`: `Arr` ends in a flexible array member,
/// and initialising one statically is a GNU extension. The layout is the
/// same -- header, length, then the slots -- and the runtime only ever sees
/// the object through an `Obj *` in its own translation unit.
fn emit_statics(o: &mut String, m: &Module) {
    use crate::ir::{StaticObj, StaticSlot};
    let slot = |s: &StaticSlot| match s {
        StaticSlot::Word(v) if *v == i64::MIN => "INT64_MIN".to_string(),
        StaticSlot::Word(v) => format!("INT64_C({v})"),
        StaticSlot::Str(i) => format!("(int64_t)(intptr_t)&str{i}"),
        StaticSlot::Obj(i) => format!("(int64_t)(intptr_t)&k{i}"),
    };
    // Eight to a line: the float-formatting table has 684 entries, and one
    // line of it would be unreadable in a debugger.
    let rows = |items: Vec<String>| -> String {
        items
            .chunks(8)
            .map(|c| format!("        {}", c.join(", ")))
            .collect::<Vec<_>>()
            .join(",\n")
    };
    for (i, k) in m.statics.iter().enumerate() {
        match k {
            StaticObj::Array { refs, slots } => {
                let ti = if *refs {
                    "rt_arr_ref_type"
                } else {
                    "rt_arr_val_type"
                };
                // A zero-length array member is not standard C either, so an
                // empty constant carries one slot it never reads.
                let cap = slots.len().max(1);
                let body = if slots.is_empty() {
                    "        0".to_string()
                } else {
                    rows(slots.iter().map(slot).collect())
                };
                writeln!(
                    o,
                    "static const struct {{ Obj hdr; int64_t len; int64_t data[{cap}]; }} \
                     k{i} __attribute__((unused)) = {{\n    {{ RC_IMMORTAL, &{ti} }}, {},\n    {{\n{body}\n    }}\n}};",
                    slots.len()
                )
                .unwrap();
            }
            // The slots in a buffer of their own, as `rt_list_new` keeps
            // them, with `cap` equal to `len`: nothing will ever push.
            StaticObj::List { refs, slots } => {
                let ti = if *refs {
                    "rt_lst_ref_type"
                } else {
                    "rt_lst_val_type"
                };
                let data = if slots.is_empty() {
                    "NULL".to_string()
                } else {
                    writeln!(
                        o,
                        "static const int64_t k{i}_data[{}] = {{\n{}\n}};",
                        slots.len(),
                        rows(slots.iter().map(slot).collect())
                    )
                    .unwrap();
                    format!("(int64_t *)k{i}_data")
                };
                writeln!(
                    o,
                    "static const Lst k{i} __attribute__((unused)) = \
                     {{ {{ RC_IMMORTAL, &{ti} }}, {n}, {n}, {data} }};",
                    n = slots.len()
                )
                .unwrap();
            }
            // `data` is never NULL for a bytes (rt.h), so an empty one still
            // points at a byte it never reads.
            StaticObj::Bytes(bs) => {
                let body: Vec<String> = if bs.is_empty() {
                    vec!["0".to_string()]
                } else {
                    bs.iter().map(|b| b.to_string()).collect()
                };
                writeln!(
                    o,
                    "static const uint8_t k{i}_data[{}] = {{\n{}\n}};",
                    body.len(),
                    rows(body)
                )
                .unwrap();
                writeln!(
                    o,
                    "static const Bytes k{i} __attribute__((unused)) = \
                     {{ {{ RC_IMMORTAL, &rt_bytes_type }}, {n}, {n}, (uint8_t *)k{i}_data }};",
                    n = bs.len()
                )
                .unwrap();
            }
            StaticObj::Map {
                key_is_str,
                val_is_ref,
                len,
                table,
            } => {
                // An empty map has no table at all, which is also how
                // `rt_map_new` leaves one until its first `set`.
                let slots_ref = if table.is_empty() {
                    "NULL".to_string()
                } else {
                    let entries: Vec<String> = table
                        .iter()
                        .map(|e| match e {
                            Some((k, v)) => format!("{{ {}, {}, SLOT_FULL }}", slot(k), slot(v)),
                            None => "{ 0, 0, SLOT_EMPTY }".to_string(),
                        })
                        .collect();
                    writeln!(
                        o,
                        "static const MapSlot k{i}_slots[{}] = {{\n{}\n}};",
                        table.len(),
                        rows(entries)
                    )
                    .unwrap();
                    format!("(MapSlot *)k{i}_slots")
                };
                // `used` is `len`: nothing was ever removed, so there are no
                // tombstones. The key is a reference exactly when it is a str.
                writeln!(
                    o,
                    "static const Map k{i} __attribute__((unused)) = \
                     {{ {{ RC_IMMORTAL, &rt_map_type }}, {slots_ref}, {cap}, {len}, {len}, \
                     {ks}, {ks}, {vr} }};",
                    cap = table.len(),
                    ks = key_is_str,
                    vr = val_is_ref,
                )
                .unwrap();
            }
        }
    }
    if !m.statics.is_empty() {
        o.push('\n');
    }
}

/// Turn an IR function name into a C identifier.
///
/// Monomorphisation mangles with `$` (`unwrap$int`), methods are qualified
/// with `.` (`Rect.area`), and the synthesised entry point is `$main`. None
/// of those are valid in standard C -- gcc and clang accept `$` as a GNU
/// extension, but the whole point of the C backend is reaching compilers we
/// have not tested.
///
/// The two escapes are different lengths on purpose, so `a$b` and `a.b`
/// cannot both become the same C name. `emit` asserts no collision anyway.
/// The body of an enum's drop or walk: which payload slots hold references
/// depends on the tag, so both have to switch on it.
///
/// `action` is a template with `{k}` standing for the slot number. Only the
/// variants that actually carry a reference get a case; the rest fall to the
/// default and do nothing.
fn emit_enum_slot_switch(o: &mut String, t: &TypeDef, action: &str) {
    let any = t.variants.iter().any(|v| v.payload.contains(&IrTy::Ref));
    if !any {
        return;
    }
    writeln!(o, "    switch (p->tag) {{").unwrap();
    for (tag, v) in t.variants.iter().enumerate() {
        if !v.payload.contains(&IrTy::Ref) {
            continue;
        }
        writeln!(o, "    case {tag}:").unwrap();
        for (k, pty) in v.payload.iter().enumerate() {
            if *pty == IrTy::Ref {
                writeln!(o, "        {}", action.replace("{k}", &k.to_string())).unwrap();
            }
        }
        writeln!(o, "        break;").unwrap();
    }
    // Every other tag carries no reference. Named so the C compiler does not
    // warn about the enumeration being incompletely handled.
    writeln!(o, "    default: break;").unwrap();
    writeln!(o, "    }}").unwrap();
}

/// Put a value into a generic slot -- a collection's element, an enum's
/// payload -- which is always one machine word.
///
/// A reference rides as its pointer. A double does NOT fit by conversion,
/// only by bit pattern, so it goes through rt_f2i; `(int64_t)3.5` would
/// store 3.
fn to_slot(expr: &str, t: IrTy) -> String {
    match t {
        IrTy::Ref => format!("(int64_t)(intptr_t){expr}"),
        IrTy::F64 => format!("rt_f2i({expr})"),
        _ => format!("(int64_t){expr}"),
    }
}

/// Read a value back out of a generic slot, undoing `to_slot`.
fn from_slot(expr: &str, t: IrTy) -> String {
    match t {
        IrTy::Ref => format!("(Obj *)(intptr_t){expr}"),
        IrTy::F64 => format!("rt_i2f({expr})"),
        IrTy::I1 => format!("(bool){expr}"),
        IrTy::I64 => expr.to_string(),
    }
}

fn c_name(name: &str) -> String {
    format!("fn_{}", c_ident(name))
}

/// The identifier-safe spelling of a source or synthesised name.
///
/// Monomorphisation mangles with `$` (`Map$str$int`, and the container's
/// synthesised fields `$t0`, `$t1`), and `$` is not a valid identifier
/// character in standard C -- gcc and clang take it as a GNU extension, and
/// refuse under `-fno-dollars-in-identifiers` or `-pedantic`. Function names
/// were already escaped here; field names were being written raw.
pub fn c_ident(name: &str) -> String {
    name.replace('$', "__")
        .replace('.', "___")
        .replace('#', "____")
}

fn signature(f: &crate::ir::Func) -> String {
    let ret = match f.ret {
        Some(t) => t.c_name(),
        None => "void",
    };
    // A parameter the body never reads is the author's choice, not a defect
    // in the emitter -- a method may legitimately ignore its receiver. The
    // warning gate exists to catch emitter bugs, so this one is suppressed
    // rather than allowed to fail a user's build.
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            // After the declarator, not before it: clang accepts either
            // placement, gcc only this one. The gcc/clang differential
            // caught that.
            format!("{} {} __attribute__((unused))", f.ty_of(*p).c_name(), p)
        })
        .collect();
    let plist = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };
    // A space only where the type does not already end in `*`.
    let sep = if ret.ends_with('*') { "" } else { " " };
    format!("{ret}{sep}{}({plist})", c_name(&f.name))
}

fn emit_func(o: &mut String, f: &crate::ir::Func, types: &[TypeDef]) {
    // Blocks are emitted in order and control falls into the first one, so
    // the entry block must be first or the function starts in the wrong place.
    assert_eq!(
        f.blocks.first().map(|b| b.id),
        Some(f.entry),
        "entry block must be emitted first"
    );
    writeln!(o, "{} {{", signature(f)).unwrap();

    // A block parameter is allowed to be dead: a merge point carries every
    // variable the arms disagree about, and nothing is obliged to read them
    // afterwards. A loop that mutates `i` but only uses `found` after the
    // loop produces exactly this. Mark those declarations so -Wunused-but-set
    // stays meaningful for ordinary instruction results, where a dead value
    // really would indicate a lowering bug.
    let block_params: std::collections::BTreeSet<Value> = f
        .blocks
        .iter()
        .flat_map(|b| b.params.iter().copied())
        .collect();

    // A value nothing reads is legitimate in emitted code: a loop whose body
    // always returns still computes the index increment its back edge would
    // have used, and that edge does not exist. gcc warns, run.sh treats a
    // warning as failure, so such a declaration says it may be unused. A dead
    // value is not a defect the way a dead *label* was.
    let mut read: std::collections::BTreeSet<Value> = std::collections::BTreeSet::new();
    for b in &f.blocks {
        for i in &b.insts {
            match i {
                Inst::Arith { lhs, rhs, .. } => {
                    read.insert(*lhs);
                    read.insert(*rhs);
                }
                // A comparison of a value with itself is emitted as the
                // constant it must be, so it reads neither operand. This has
                // to agree with the emission below or the operand is declared
                // used and then never used, which is its own warning.
                Inst::ICmp { lhs, rhs, .. } => {
                    if lhs != rhs || f.ty_of(*lhs) == IrTy::F64 {
                        read.insert(*lhs);
                        read.insert(*rhs);
                    }
                }
                Inst::Not { src, .. } => {
                    read.insert(*src);
                }
                Inst::Call { args, .. }
                | Inst::CallIface { args, .. }
                | Inst::Spawn { args, .. } => read.extend(args.iter().copied()),
                Inst::LoadField { obj, .. } => {
                    read.insert(*obj);
                }
                Inst::FConst { .. } => {}
                Inst::ParseInto { src, .. } => {
                    read.insert(*src);
                }
                Inst::EnumPack { args, .. } => read.extend(args.iter().copied()),
                Inst::EnumTag { obj, .. } | Inst::EnumPayload { obj, .. } => {
                    read.insert(*obj);
                }
                Inst::StoreField { obj, val, .. } => {
                    read.insert(*obj);
                    read.insert(*val);
                }
                Inst::RcInc { val } | Inst::RcDec { val } => {
                    read.insert(*val);
                }
                Inst::IConst { .. }
                | Inst::BConst { .. }
                | Inst::SConst { .. }
                | Inst::KConst { .. }
                | Inst::Alloc { .. } => {}
            }
        }
        match &b.term {
            Term::Jump { args, .. } => read.extend(args.iter().copied()),
            Term::Brif {
                cond,
                then_args,
                els_args,
                ..
            } => {
                read.insert(*cond);
                read.extend(then_args.iter().copied());
                read.extend(els_args.iter().copied());
            }
            Term::Ret { val: Some(v) } => {
                read.insert(*v);
            }
            Term::Ret { val: None } => {}
        }
    }

    // Declare every value up front. Function parameters are already declared
    // by the signature, so skip those.
    let is_param = |v: Value| f.params.contains(&v);
    for (i, t) in f.types.iter().enumerate() {
        let v = Value(i as u32);
        if is_param(v) {
            continue;
        }
        let name = t.c_name();
        let sep = if name.ends_with('*') { "" } else { " " };
        // Initialised to silence -Wmaybe-uninitialized: a value defined in one
        // arm of a branch is only read on paths that define it, but the C
        // compiler cannot always see that, and run.sh treats warnings as
        // failures.
        let zero = match t {
            IrTy::I64 => "0",
            IrTy::F64 => "0.0",
            IrTy::I1 => "false",
            IrTy::Ref => "NULL",
        };
        let attr = if block_params.contains(&v) || !read.contains(&v) {
            "__attribute__((unused)) "
        } else {
            ""
        };
        writeln!(o, "    {attr}{name}{sep}{v} = {zero};").unwrap();
    }
    if f.types.len() > f.params.len() {
        o.push('\n');
    }

    // Only blocks that are actually jumped to get a label. C warns about
    // unused labels, run.sh treats warnings as failures, and the entry block
    // is fallen into rather than branched to.
    let mut targeted = std::collections::BTreeSet::new();
    for b in &f.blocks {
        match &b.term {
            Term::Jump { to, .. } => {
                targeted.insert(*to);
            }
            Term::Brif { then, els, .. } => {
                targeted.insert(*then);
                targeted.insert(*els);
            }
            Term::Ret { .. } => {}
        }
    }

    for b in &f.blocks {
        if targeted.contains(&b.id) {
            writeln!(o, "b{}:; /* {} */", b.id.0, b.id).unwrap();
        } else if b.id != f.entry {
            writeln!(o, "    /* {} (unreachable) */", b.id).unwrap();
        }
        for i in &b.insts {
            emit_inst(o, f, types, i);
        }
        emit_term(o, f, &b.term);
    }

    writeln!(o, "}}").unwrap();
}

fn emit_inst(o: &mut String, f: &crate::ir::Func, types: &[TypeDef], i: &Inst) {
    match i {
        Inst::FConst { dst, val } => {
            // 17 significant digits round-trips any double exactly, and the
            // hex form would be exact but unreadable in emitted source.
            // `inf` and `nan` cannot appear: a literal that does not fit is
            // rejected by the lexer, and arithmetic producing them happens at
            // run time, not here.
            writeln!(o, "    {dst} = {val:.17e};").unwrap();
        }
        Inst::IConst { dst, val } => {
            // INT64_MIN has no positive literal form in C; write it as an
            // expression the preprocessor already defines correctly.
            if *val == i64::MIN {
                writeln!(o, "    {dst} = INT64_MIN;").unwrap();
            } else {
                writeln!(o, "    {dst} = INT64_C({val});").unwrap();
            }
        }
        Inst::BConst { dst, val } => {
            writeln!(o, "    {dst} = {};", if *val { "true" } else { "false" }).unwrap();
        }
        Inst::SConst { dst, idx } => {
            writeln!(o, "    {dst} = (Obj *)&str{idx};").unwrap();
        }
        // The static is `const` -- it lives in read-only memory -- and an
        // `Obj *` is not. Casting the qualifier away is defined as long as
        // nothing writes through the pointer, and nothing does: the refcount
        // operations return early on RC_IMMORTAL, and every runtime path that
        // would change a collection traps on one first (runtime/rt.c,
        // `rt_check_mutable`).
        Inst::KConst { dst, idx } => {
            writeln!(o, "    {dst} = (Obj *)&k{idx};").unwrap();
        }
        Inst::Arith { dst, op, lhs, rhs } => {
            if f.ty_of(*dst) == IrTy::F64 {
                // IEEE: no trap, no checked helper. Overflow is an infinity
                // and 0.0/0.0 is a NaN, which is the defined answer rather
                // than a fault -- unlike the integer case, where wrapping
                // would be the silent wrong answer.
                writeln!(o, "    {dst} = {lhs} {} {rhs};", op.c_op()).unwrap();
            } else {
                writeln!(o, "    {dst} = {}({lhs}, {rhs});", op.rt_fn()).unwrap();
            }
        }
        Inst::ICmp { dst, cmp, lhs, rhs } => {
            // NOT for a float: `x == x` is FALSE when x is a NaN, so the
            // answer does depend on the value and the fold would be wrong.
            // The C compilers do not warn about a self-comparison on a
            // double for exactly the same reason.
            if lhs == rhs && f.ty_of(*lhs) != IrTy::F64 {
                // `x == x` is a warning under -Wall (-Wtautological-compare)
                // on both gcc and clang, and the warning gate reads any
                // warning as a failure. The answer does not depend on the
                // value, so emit the answer. Comparing a name with itself is
                // odd but legal, and the emitter is not the place to say so.
                let val = cmp.holds_for_equal_operands();
                writeln!(o, "    {dst} = {};", if val { "true" } else { "false" }).unwrap();
            } else {
                writeln!(o, "    {dst} = ({lhs} {} {rhs});", cmp.c_op()).unwrap();
            }
        }
        Inst::Not { dst, src } => {
            writeln!(o, "    {dst} = !{src};").unwrap();
        }
        Inst::Call { dst, func, args } => {
            // Runtime helpers are already C names; user functions are IR
            // names and need escaping and the prefix.
            let callee = if func.starts_with("rt_") {
                func.clone()
            } else {
                c_name(func)
            };
            // The channel runtime is typed in terms of Chan *, and a slot is
            // 64 bits: the compiler knows the element type statically, so a
            // reference rides as its pointer with no tagging.
            let a: Vec<String> = args
                .iter()
                .enumerate()
                .map(|(i, v)| match (func.as_str(), i) {
                    ("rt_chan_send", 0) | ("rt_chan_recv", 0) | ("rt_chan_close", 0) => {
                        format!("(Chan *){v}")
                    }
                    // Everything below takes a generic slot: one machine
                    // word whatever the element type is.
                    ("rt_chan_send", 1)
                    | ("rt_index_set", 2)
                    | ("rt_list_push", 1)
                    | ("rt_list_insert", 2)
                    | ("rt_seq_contains", 1)
                    | ("rt_seq_index_of", 1)
                    | ("rt_array_new", 1)
                    | ("rt_list_repeat", 1)
                    | ("rt_array_put", 2)
                    | ("rt_map_set", 1)
                    | ("rt_map_set", 2)
                    | ("rt_map_get", 1)
                    | ("rt_map_has", 1)
                    | ("rt_map_remove", 1)
                        if matches!(f.ty_of(*v), IrTy::Ref | IrTy::F64) =>
                    {
                        to_slot(&v.to_string(), f.ty_of(*v))
                    }
                    _ => v.to_string(),
                })
                .collect();
            match dst {
                Some(d)
                    if matches!(
                        func.as_str(),
                        "rt_chan_recv"
                            | "rt_index_get"
                            | "rt_list_pop"
                            | "rt_list_remove_at"
                            | "rt_map_get"
                    ) && matches!(f.ty_of(*d), IrTy::Ref | IrTy::F64) =>
                {
                    let call = format!("{callee}({})", a.join(", "));
                    writeln!(o, "    {d} = {};", from_slot(&call, f.ty_of(*d))).unwrap()
                }
                Some(d)
                    if matches!(
                        func.as_str(),
                        "rt_chan_new"
                            | "rt_array_new"
                            | "rt_array_blank"
                            | "rt_list_new"
                            | "rt_list_repeat"
                            | "rt_map_keys"
                            | "rt_map_values"
                    ) =>
                {
                    writeln!(o, "    {d} = (Obj *){callee}({});", a.join(", ")).unwrap()
                }
                Some(d) => writeln!(o, "    {d} = {callee}({});", a.join(", ")).unwrap(),
                None => writeln!(o, "    {callee}({});", a.join(", ")).unwrap(),
            }
        }
        Inst::Alloc { dst, tid } => {
            writeln!(o, "    {dst} = rt_alloc(sizeof(T{tid}), &ti_T{tid});").unwrap();
        }
        Inst::EnumPack {
            dst,
            tid,
            tag,
            args,
        } => {
            writeln!(o, "    {dst} = rt_alloc(sizeof(T{tid}), &ti_T{tid});").unwrap();
            writeln!(o, "    ((T{tid} *){dst})->tag = {tag};").unwrap();
            for (k, a) in args.iter().enumerate() {
                let v = to_slot(&a.to_string(), f.ty_of(*a));
                writeln!(o, "    ((T{tid} *){dst})->p{k} = {v};").unwrap();
            }
        }
        Inst::ParseInto { ok, dst, func, src } => {
            writeln!(o, "    {ok} = {func}({src}, &{dst});").unwrap();
        }
        Inst::EnumTag { dst, obj, tid } => {
            writeln!(o, "    {dst} = ((T{tid} *){obj})->tag;").unwrap();
        }
        Inst::EnumPayload { dst, obj, tid, idx } => {
            // The slot is a machine word whatever it holds; the destination's
            // type says how to read it, and the lowering only emits this
            // where the tag is already known.
            let raw = format!("((T{tid} *){obj})->p{idx}");
            writeln!(o, "    {dst} = {};", from_slot(&raw, f.ty_of(*dst))).unwrap();
        }
        Inst::LoadField { dst, obj, tid, idx } => {
            let name = c_ident(&types[*tid as usize].fields[*idx as usize].0);
            writeln!(o, "    {dst} = ((T{tid} *){obj})->f_{name};").unwrap();
        }
        Inst::StoreField { obj, tid, idx, val } => {
            let name = c_ident(&types[*tid as usize].fields[*idx as usize].0);
            writeln!(o, "    ((T{tid} *){obj})->f_{name} = {val};").unwrap();
        }
        Inst::CallIface {
            dst,
            slot,
            name,
            args,
            ret,
        } => {
            // The slot is cast back to its real signature here; only the
            // indirection is dynamic, and the compiler checked the signature
            // structurally before emitting this.
            let rty = match ret {
                Some(t) => t.c_name(),
                None => "void",
            };
            let ptypes: Vec<&str> = args.iter().map(|a| f.ty_of(*a).c_name()).collect();
            let a: Vec<String> = args.iter().map(|v| v.to_string()).collect();
            let recv = &a[0];
            let cast = format!("({rty} (*)({}))", ptypes.join(", "));
            let call = format!("({cast}{recv}->ty->vtable[{slot}])({})", a.join(", "));
            match dst {
                Some(d) => writeln!(o, "    {d} = {call}; /* .{name} */").unwrap(),
                None => writeln!(o, "    {call}; /* .{name} */").unwrap(),
            }
        }
        Inst::Spawn { func, args } => {
            let a: Vec<String> = args.iter().map(|v| v.to_string()).collect();
            writeln!(o, "    {{").unwrap();
            writeln!(
                o,
                "        spawn_{0} *sa = malloc(sizeof(spawn_{0}));",
                c_name(func)
            )
            .unwrap();
            writeln!(o, "        if (sa == NULL) rt_trap(\"out of memory\");").unwrap();
            for (i, x) in a.iter().enumerate() {
                writeln!(o, "        sa->a{i} = {x};").unwrap();
            }
            writeln!(o, "        rt_spawn(trampoline_{}, sa);", c_name(func)).unwrap();
            writeln!(o, "    }}").unwrap();
        }
        Inst::RcInc { val } => writeln!(o, "    rc_inc({val});").unwrap(),
        Inst::RcDec { val } => writeln!(o, "    rc_dec({val});").unwrap(),
    }
    let _ = f;
}

/// Emit a jump, moving block arguments into the target's parameters.
///
/// Every argument goes through a temporary first. That is the general fix for
/// the parallel-copy problem -- `jump b(p1, p0)` would corrupt both values if
/// assigned in sequence -- and it costs nothing, because the C compiler
/// removes the redundant copies. docs/ir-v0.md §7.2 flags this as a trap worth
/// not being clever about.
fn emit_jump(o: &mut String, f: &crate::ir::Func, to: crate::ir::BlockId, args: &[Value]) {
    let target = f.block(to);
    debug_assert_eq!(
        target.params.len(),
        args.len(),
        "block argument arity mismatch"
    );
    if args.is_empty() {
        writeln!(o, "    goto b{};", to.0).unwrap();
        return;
    }
    writeln!(o, "    {{").unwrap();
    for (n, a) in args.iter().enumerate() {
        let t = f.ty_of(*a);
        let name = t.c_name();
        let sep = if name.ends_with('*') { "" } else { " " };
        writeln!(o, "        {name}{sep}tmp{n} = {a};").unwrap();
    }
    for (n, p) in target.params.iter().enumerate() {
        writeln!(o, "        {p} = tmp{n};").unwrap();
    }
    writeln!(o, "        goto b{};", to.0).unwrap();
    writeln!(o, "    }}").unwrap();
}

fn emit_term(o: &mut String, f: &crate::ir::Func, t: &Term) {
    match t {
        Term::Jump { to, args } => emit_jump(o, f, *to, args),
        Term::Brif {
            cond,
            then,
            then_args,
            els,
            els_args,
        } => {
            writeln!(o, "    if ({cond}) {{").unwrap();
            emit_jump(o, f, *then, then_args);
            writeln!(o, "    }} else {{").unwrap();
            emit_jump(o, f, *els, els_args);
            writeln!(o, "    }}").unwrap();
        }
        Term::Ret { val: Some(v) } => writeln!(o, "    return {v};").unwrap(),
        // A valueless return in a function that returns something is the
        // lowering's filler for an UNREACHABLE block -- every arm of an `if`
        // or a `match` already returned, so the join has no predecessor. C
        // rejects a bare `return` there, so say what it means instead:
        // rt_trap is _Noreturn, which also satisfies C that the function
        // cannot fall off its end.
        Term::Ret { val: None } if f.ret.is_some() => {
            writeln!(o, "    rt_trap(\"unreachable\");").unwrap()
        }
        Term::Ret { val: None } => writeln!(o, "    return;").unwrap(),
    }
}

/// Render bytes as a C string literal. Escapes conservatively: anything
/// outside printable ASCII becomes an octal escape, which avoids both
/// encoding assumptions and the `\x` ambiguity where a following hex digit
/// would extend the escape.
fn c_string_literal(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() + 2);
    s.push('"');
    for &b in bytes {
        match b {
            b'"' => s.push_str("\\\""),
            b'\\' => s.push_str("\\\\"),
            b'\n' => s.push_str("\\n"),
            b'\t' => s.push_str("\\t"),
            b'\r' => s.push_str("\\r"),
            // A `?` is escaped so `??x` can never appear in the emitted
            // literal. `??!` and friends are trigraphs: C99 replaces them,
            // and both gcc and clang warn under -Wall that they are ignoring
            // one -- which the warning gate reads as a failure. `\?` is the
            // same character and cannot start a trigraph.
            b'?' => s.push_str("\\?"),
            0x20..=0x7e => s.push(b as char),
            other => {
                write!(s, "\\{:03o}", other).unwrap();
            }
        }
    }
    s.push('"');
    s
}

impl ArithOp {
    #[allow(dead_code)]
    fn is_checked(self) -> bool {
        true
    }
}
