//! C backend.
//!
//! Consumes post-refcount IR and emits a single translation unit. It does no
//! reasoning about ownership -- every rc_inc and rc_dec it emits was already
//! placed by the lowering pass (docs/ir-v0.md §4).
//!
//! The runtime is linked separately and is NOT included here beyond its
//! header; see docs/ir-v0.md §7.1 for why that separation is load-bearing.

use std::fmt::Write;

use crate::ir::{ArithOp, Inst, IrTy, Module, Term, TypeDef, Value};

pub fn emit(m: &Module) -> String {
    let mut o = String::new();

    o.push_str("/* Generated by langc. Do not edit. */\n");
    o.push_str("#include \"rt.h\"\n#include <stdint.h>\n#include <stdlib.h>\n\n");

    // One C struct per user type. Every object starts with the Obj header, so
    // a `ref` is always an `Obj *` and the field access casts.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface {
            writeln!(
                o,
                "/* interface {} -- no layout; values are Obj * */",
                t.name
            )
            .unwrap();
            continue;
        }
        writeln!(o, "/* {} */", t.name).unwrap();
        writeln!(o, "typedef struct {{").unwrap();
        writeln!(o, "    Obj hdr;").unwrap();
        for (fname, fty) in &t.fields {
            let c = fty.c_name();
            let sep = if c.ends_with('*') { "" } else { " " };
            let fname = c_ident(fname);
            writeln!(o, "    {c}{sep}f_{fname};").unwrap();
        }
        writeln!(o, "}} T{i};").unwrap();
    }
    if !m.types.is_empty() {
        o.push('\n');
    }

    // A drop function only exists for types that hold references; rc_dec
    // checks for NULL, so types holding none pay a branch instead of a call.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct || !t.needs_drop() {
            continue;
        }
        writeln!(o, "static void drop_T{i}(Obj *o) {{").unwrap();
        writeln!(o, "    T{i} *p = (T{i} *)o;").unwrap();
        for (fname, fty) in &t.fields {
            if *fty == IrTy::Ref {
                let fname = c_ident(fname);
                writeln!(o, "    rc_dec(p->f_{fname});").unwrap();
            }
        }
        writeln!(o, "}}").unwrap();
    }
    if m.types.iter().any(TypeDef::needs_drop) {
        o.push('\n');
    }

    // A walk function reports the references an object holds, without
    // releasing them. rt_check_unique uses it to decide whether the whole
    // graph reachable from a value crossing a thread boundary is reachable
    // from anywhere else -- see runtime/rt.c. Same condition as the drop
    // function: a type with no reference fields needs neither.
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct || !t.needs_drop() {
            continue;
        }
        writeln!(
            o,
            "static void walk_T{i}(Obj *o, VisitFn visit, void *ctx) {{"
        )
        .unwrap();
        writeln!(o, "    T{i} *p = (T{i} *)o;").unwrap();
        for (fname, fty) in &t.fields {
            if *fty == IrTy::Ref {
                let fname = c_ident(fname);
                writeln!(o, "    visit(ctx, p->f_{fname});").unwrap();
            }
        }
        writeln!(o, "}}").unwrap();
    }
    if m.types.iter().any(TypeDef::needs_drop) {
        o.push('\n');
    }

    // One TypeInfo per concrete type: its drop function and its vtable. The
    // vtable has one slot per distinct interface method name in the program,
    // so a dispatch index is a compile-time constant.
    if !m.types.is_empty() {
        for f in &m.funcs {
            writeln!(o, "{};", signature(f)).unwrap();
        }
        o.push('\n');
    }
    for (i, t) in m.types.iter().enumerate() {
        if t.is_interface || t.is_chan || t.is_distinct {
            continue;
        }
        let (drop, walk) = if t.needs_drop() {
            (format!("drop_T{i}"), format!("walk_T{i}"))
        } else {
            ("NULL".to_string(), "NULL".to_string())
        };
        if m.iface_slots.is_empty() {
            writeln!(
                o,
                "static const TypeInfo ti_T{i} __attribute__((unused)) = \
                 {{ {drop}, NULL, {walk} }};"
            )
            .unwrap();
        } else {
            let entries: Vec<String> = t
                .vtable
                .iter()
                .map(|e| match e {
                    Some(fname) => format!("(AnyFn){}", c_name(fname)),
                    None => "NULL".to_string(),
                })
                .collect();
            writeln!(
                o,
                "static const AnyFn vt_T{i}[] __attribute__((unused)) = {{ {} }};",
                entries.join(", ")
            )
            .unwrap();
            writeln!(
                o,
                "static const TypeInfo ti_T{i} __attribute__((unused)) = \
                 {{ {drop}, vt_T{i}, {walk} }};"
            )
            .unwrap();
        }
    }
    if !m
        .types
        .iter()
        .all(|t| t.is_interface || t.is_chan || t.is_distinct)
    {
        o.push('\n');
    }

    // String literals are immortal: static storage, RC_IMMORTAL, never freed.
    for (i, s) in m.strings.iter().enumerate() {
        let bytes = s.as_bytes();
        writeln!(
            o,
            "static Str str{i} = {{ {{ RC_IMMORTAL, &rt_str_type }}, {}, {} }};",
            bytes.len(),
            c_string_literal(bytes)
        )
        .unwrap();
    }
    if !m.strings.is_empty() {
        o.push('\n');
    }

    // Escaping `$` could collide two distinct IR names, and a collision here
    // is a silent miscompile. `lower` rejects it with a proper diagnostic
    // before we get this far -- see `check_c_name_collisions` -- so reaching
    // this assertion means that check has a hole, not that the user did
    // something wrong.
    {
        let mut seen = std::collections::BTreeSet::new();
        for f in &m.funcs {
            assert!(
                seen.insert(c_name(&f.name)),
                "two functions map to the same C name: {} \
                 (lower::check_c_name_collisions should have caught this)",
                c_name(&f.name)
            );
        }
    }

    // Prototypes first, so definition order does not constrain call order.
    for f in &m.funcs {
        writeln!(o, "{};", signature(f)).unwrap();
    }
    o.push('\n');

    // One argument struct and one trampoline per spawned function. pthreads
    // takes a single void*, so the arguments are packed on the heap and the
    // trampoline unpacks them.
    let mut spawned: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for f in &m.funcs {
        for b in &f.blocks {
            for i in &b.insts {
                if let Inst::Spawn { func, .. } = i {
                    spawned.insert(func.as_str());
                }
            }
        }
    }
    for name in &spawned {
        let target = m
            .funcs
            .iter()
            .find(|f| f.name == **name)
            .expect("spawned function must exist");
        let cn = c_name(name);
        writeln!(o, "typedef struct {{").unwrap();
        for (i, p) in target.params.iter().enumerate() {
            let t = target.ty_of(*p).c_name();
            let sep = if t.ends_with('*') { "" } else { " " };
            writeln!(o, "    {t}{sep}a{i};").unwrap();
        }
        if target.params.is_empty() {
            writeln!(o, "    int unused;").unwrap();
        }
        writeln!(o, "}} spawn_{cn};").unwrap();
        writeln!(o, "static void *trampoline_{cn}(void *p) {{").unwrap();
        writeln!(o, "    spawn_{cn} *a = (spawn_{cn} *)p;").unwrap();
        let passed: Vec<String> = (0..target.params.len())
            .map(|i| format!("a->a{i}"))
            .collect();
        writeln!(o, "    {cn}({});", passed.join(", ")).unwrap();
        // The spawning side handed this thread a reference per argument --
        // moved if it owned one, retained if it only borrowed. Parameters are
        // borrowed inside the callee (docs/ir-v0.md §5.1), so nobody there
        // will release them: the trampoline is where the transfer ends.
        for (i, p) in target.params.iter().enumerate() {
            if target.ty_of(*p) == IrTy::Ref {
                writeln!(o, "    rc_dec(a->a{i});").unwrap();
            }
        }
        writeln!(o, "    free(a);").unwrap();
        writeln!(o, "    return NULL;").unwrap();
        writeln!(o, "}}").unwrap();
    }
    if !spawned.is_empty() {
        o.push('\n');
    }

    for f in &m.funcs {
        emit_func(&mut o, f, &m.types);
        o.push('\n');
    }

    // rt_wait_all joins every spawned thread. Without it a spawn can
    // outlive the program: its output is lost, and the refcount invariant
    // is reported by atexit while threads are still running.
    writeln!(
        o,
        "int main(void) {{
    {}();
    rt_wait_all();
    return 0;
}}",
        c_name("$main")
    )
    .unwrap();
    o
}

/// Turn an IR function name into a C identifier.
///
/// Monomorphisation mangles with `$` (`unwrap$int`), methods are qualified
/// with `.` (`Rect.area`), and the synthesised entry point is `$main`. None
/// of those are valid in standard C -- gcc and clang accept `$` as a GNU
/// extension, but the whole point of the C backend is reaching compilers we
/// have not tested.
///
/// The two escapes are different lengths on purpose, so `a$b` and `a.b`
/// cannot both become the same C name. `emit` asserts no collision anyway.
fn c_name(name: &str) -> String {
    format!("fn_{}", c_ident(name))
}

/// The identifier-safe spelling of a source or synthesised name.
///
/// Monomorphisation mangles with `$` (`Map$str$int`, and the container's
/// synthesised fields `$t0`, `$t1`), and `$` is not a valid identifier
/// character in standard C -- gcc and clang take it as a GNU extension, and
/// refuse under `-fno-dollars-in-identifiers` or `-pedantic`. Function names
/// were already escaped here; field names were being written raw.
pub fn c_ident(name: &str) -> String {
    name.replace('$', "__").replace('.', "___")
}

fn signature(f: &crate::ir::Func) -> String {
    let ret = match f.ret {
        Some(t) => t.c_name(),
        None => "void",
    };
    // A parameter the body never reads is the author's choice, not a defect
    // in the emitter -- a method may legitimately ignore its receiver. The
    // warning gate exists to catch emitter bugs, so this one is suppressed
    // rather than allowed to fail a user's build.
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            // After the declarator, not before it: clang accepts either
            // placement, gcc only this one. The gcc/clang differential
            // caught that.
            format!("{} {} __attribute__((unused))", f.ty_of(*p).c_name(), p)
        })
        .collect();
    let plist = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };
    // A space only where the type does not already end in `*`.
    let sep = if ret.ends_with('*') { "" } else { " " };
    format!("{ret}{sep}{}({plist})", c_name(&f.name))
}

fn emit_func(o: &mut String, f: &crate::ir::Func, types: &[TypeDef]) {
    // Blocks are emitted in order and control falls into the first one, so
    // the entry block must be first or the function starts in the wrong place.
    assert_eq!(
        f.blocks.first().map(|b| b.id),
        Some(f.entry),
        "entry block must be emitted first"
    );
    writeln!(o, "{} {{", signature(f)).unwrap();

    // A block parameter is allowed to be dead: a merge point carries every
    // variable the arms disagree about, and nothing is obliged to read them
    // afterwards. A loop that mutates `i` but only uses `found` after the
    // loop produces exactly this. Mark those declarations so -Wunused-but-set
    // stays meaningful for ordinary instruction results, where a dead value
    // really would indicate a lowering bug.
    let block_params: std::collections::BTreeSet<Value> = f
        .blocks
        .iter()
        .flat_map(|b| b.params.iter().copied())
        .collect();

    // A value nothing reads is legitimate in emitted code: a loop whose body
    // always returns still computes the index increment its back edge would
    // have used, and that edge does not exist. gcc warns, run.sh treats a
    // warning as failure, so such a declaration says it may be unused. A dead
    // value is not a defect the way a dead *label* was.
    let mut read: std::collections::BTreeSet<Value> = std::collections::BTreeSet::new();
    for b in &f.blocks {
        for i in &b.insts {
            match i {
                Inst::Arith { lhs, rhs, .. } => {
                    read.insert(*lhs);
                    read.insert(*rhs);
                }
                // A comparison of a value with itself is emitted as the
                // constant it must be, so it reads neither operand. This has
                // to agree with the emission below or the operand is declared
                // used and then never used, which is its own warning.
                Inst::ICmp { lhs, rhs, .. } => {
                    if lhs != rhs {
                        read.insert(*lhs);
                        read.insert(*rhs);
                    }
                }
                Inst::Not { src, .. } => {
                    read.insert(*src);
                }
                Inst::Call { args, .. }
                | Inst::CallIface { args, .. }
                | Inst::Spawn { args, .. } => read.extend(args.iter().copied()),
                Inst::LoadField { obj, .. } => {
                    read.insert(*obj);
                }
                Inst::StoreField { obj, val, .. } => {
                    read.insert(*obj);
                    read.insert(*val);
                }
                Inst::RcInc { val } | Inst::RcDec { val } => {
                    read.insert(*val);
                }
                Inst::IConst { .. }
                | Inst::BConst { .. }
                | Inst::SConst { .. }
                | Inst::Alloc { .. } => {}
            }
        }
        match &b.term {
            Term::Jump { args, .. } => read.extend(args.iter().copied()),
            Term::Brif {
                cond,
                then_args,
                els_args,
                ..
            } => {
                read.insert(*cond);
                read.extend(then_args.iter().copied());
                read.extend(els_args.iter().copied());
            }
            Term::Ret { val: Some(v) } => {
                read.insert(*v);
            }
            Term::Ret { val: None } => {}
        }
    }

    // Declare every value up front. Function parameters are already declared
    // by the signature, so skip those.
    let is_param = |v: Value| f.params.contains(&v);
    for (i, t) in f.types.iter().enumerate() {
        let v = Value(i as u32);
        if is_param(v) {
            continue;
        }
        let name = t.c_name();
        let sep = if name.ends_with('*') { "" } else { " " };
        // Initialised to silence -Wmaybe-uninitialized: a value defined in one
        // arm of a branch is only read on paths that define it, but the C
        // compiler cannot always see that, and run.sh treats warnings as
        // failures.
        let zero = match t {
            IrTy::I64 => "0",
            IrTy::I1 => "false",
            IrTy::Ref => "NULL",
        };
        let attr = if block_params.contains(&v) || !read.contains(&v) {
            "__attribute__((unused)) "
        } else {
            ""
        };
        writeln!(o, "    {attr}{name}{sep}{v} = {zero};").unwrap();
    }
    if f.types.len() > f.params.len() {
        o.push('\n');
    }

    // Only blocks that are actually jumped to get a label. C warns about
    // unused labels, run.sh treats warnings as failures, and the entry block
    // is fallen into rather than branched to.
    let mut targeted = std::collections::BTreeSet::new();
    for b in &f.blocks {
        match &b.term {
            Term::Jump { to, .. } => {
                targeted.insert(*to);
            }
            Term::Brif { then, els, .. } => {
                targeted.insert(*then);
                targeted.insert(*els);
            }
            Term::Ret { .. } => {}
        }
    }

    for b in &f.blocks {
        if targeted.contains(&b.id) {
            writeln!(o, "b{}:; /* {} */", b.id.0, b.id).unwrap();
        } else if b.id != f.entry {
            writeln!(o, "    /* {} (unreachable) */", b.id).unwrap();
        }
        for i in &b.insts {
            emit_inst(o, f, types, i);
        }
        emit_term(o, f, &b.term);
    }

    writeln!(o, "}}").unwrap();
}

fn emit_inst(o: &mut String, f: &crate::ir::Func, types: &[TypeDef], i: &Inst) {
    match i {
        Inst::IConst { dst, val } => {
            // INT64_MIN has no positive literal form in C; write it as an
            // expression the preprocessor already defines correctly.
            if *val == i64::MIN {
                writeln!(o, "    {dst} = INT64_MIN;").unwrap();
            } else {
                writeln!(o, "    {dst} = INT64_C({val});").unwrap();
            }
        }
        Inst::BConst { dst, val } => {
            writeln!(o, "    {dst} = {};", if *val { "true" } else { "false" }).unwrap();
        }
        Inst::SConst { dst, idx } => {
            writeln!(o, "    {dst} = (Obj *)&str{idx};").unwrap();
        }
        Inst::Arith { dst, op, lhs, rhs } => {
            writeln!(o, "    {dst} = {}({lhs}, {rhs});", op.rt_fn()).unwrap();
            let _ = op;
        }
        Inst::ICmp { dst, cmp, lhs, rhs } => {
            if lhs == rhs {
                // `x == x` is a warning under -Wall (-Wtautological-compare)
                // on both gcc and clang, and the warning gate reads any
                // warning as a failure. The answer does not depend on the
                // value, so emit the answer. Comparing a name with itself is
                // odd but legal, and the emitter is not the place to say so.
                let val = cmp.holds_for_equal_operands();
                writeln!(o, "    {dst} = {};", if val { "true" } else { "false" }).unwrap();
            } else {
                writeln!(o, "    {dst} = ({lhs} {} {rhs});", cmp.c_op()).unwrap();
            }
        }
        Inst::Not { dst, src } => {
            writeln!(o, "    {dst} = !{src};").unwrap();
        }
        Inst::Call { dst, func, args } => {
            // Runtime helpers are already C names; user functions are IR
            // names and need escaping and the prefix.
            let callee = if func.starts_with("rt_") {
                func.clone()
            } else {
                c_name(func)
            };
            // The channel runtime is typed in terms of Chan *, and a slot is
            // 64 bits: the compiler knows the element type statically, so a
            // reference rides as its pointer with no tagging.
            let a: Vec<String> = args
                .iter()
                .enumerate()
                .map(|(i, v)| match (func.as_str(), i) {
                    ("rt_chan_send", 0) | ("rt_chan_recv", 0) | ("rt_chan_close", 0) => {
                        format!("(Chan *){v}")
                    }
                    ("rt_chan_send", 1)
                    | ("rt_index_set", 2)
                    | ("rt_list_push", 1)
                    | ("rt_array_new", 1)
                    | ("rt_map_set", 1)
                    | ("rt_map_set", 2)
                    | ("rt_map_get", 1)
                    | ("rt_map_has", 1)
                    | ("rt_map_remove", 1)
                        if f.ty_of(*v) == IrTy::Ref =>
                    {
                        format!("(int64_t)(intptr_t){v}")
                    }
                    _ => v.to_string(),
                })
                .collect();
            match dst {
                Some(d)
                    if matches!(
                        func.as_str(),
                        "rt_chan_recv" | "rt_index_get" | "rt_list_pop" | "rt_map_get"
                    ) && f.ty_of(*d) == IrTy::Ref =>
                {
                    writeln!(o, "    {d} = (Obj *)(intptr_t){callee}({});", a.join(", ")).unwrap()
                }
                Some(d)
                    if matches!(
                        func.as_str(),
                        "rt_chan_new" | "rt_array_new" | "rt_list_new"
                    ) =>
                {
                    writeln!(o, "    {d} = (Obj *){callee}({});", a.join(", ")).unwrap()
                }
                Some(d) => writeln!(o, "    {d} = {callee}({});", a.join(", ")).unwrap(),
                None => writeln!(o, "    {callee}({});", a.join(", ")).unwrap(),
            }
        }
        Inst::Alloc { dst, tid } => {
            writeln!(o, "    {dst} = rt_alloc(sizeof(T{tid}), &ti_T{tid});").unwrap();
        }
        Inst::LoadField { dst, obj, tid, idx } => {
            let name = c_ident(&types[*tid as usize].fields[*idx as usize].0);
            writeln!(o, "    {dst} = ((T{tid} *){obj})->f_{name};").unwrap();
        }
        Inst::StoreField { obj, tid, idx, val } => {
            let name = c_ident(&types[*tid as usize].fields[*idx as usize].0);
            writeln!(o, "    ((T{tid} *){obj})->f_{name} = {val};").unwrap();
        }
        Inst::CallIface {
            dst,
            slot,
            name,
            args,
            ret,
        } => {
            // The slot is cast back to its real signature here; only the
            // indirection is dynamic, and the compiler checked the signature
            // structurally before emitting this.
            let rty = match ret {
                Some(t) => t.c_name(),
                None => "void",
            };
            let ptypes: Vec<&str> = args.iter().map(|a| f.ty_of(*a).c_name()).collect();
            let a: Vec<String> = args.iter().map(|v| v.to_string()).collect();
            let recv = &a[0];
            let cast = format!("({rty} (*)({}))", ptypes.join(", "));
            let call = format!("({cast}{recv}->ty->vtable[{slot}])({})", a.join(", "));
            match dst {
                Some(d) => writeln!(o, "    {d} = {call}; /* .{name} */").unwrap(),
                None => writeln!(o, "    {call}; /* .{name} */").unwrap(),
            }
        }
        Inst::Spawn { func, args } => {
            let a: Vec<String> = args.iter().map(|v| v.to_string()).collect();
            writeln!(o, "    {{").unwrap();
            writeln!(
                o,
                "        spawn_{0} *sa = malloc(sizeof(spawn_{0}));",
                c_name(func)
            )
            .unwrap();
            writeln!(o, "        if (sa == NULL) rt_trap(\"out of memory\");").unwrap();
            for (i, x) in a.iter().enumerate() {
                writeln!(o, "        sa->a{i} = {x};").unwrap();
            }
            writeln!(o, "        rt_spawn(trampoline_{}, sa);", c_name(func)).unwrap();
            writeln!(o, "    }}").unwrap();
        }
        Inst::RcInc { val } => writeln!(o, "    rc_inc({val});").unwrap(),
        Inst::RcDec { val } => writeln!(o, "    rc_dec({val});").unwrap(),
    }
    let _ = f;
}

/// Emit a jump, moving block arguments into the target's parameters.
///
/// Every argument goes through a temporary first. That is the general fix for
/// the parallel-copy problem -- `jump b(p1, p0)` would corrupt both values if
/// assigned in sequence -- and it costs nothing, because the C compiler
/// removes the redundant copies. docs/ir-v0.md §7.2 flags this as a trap worth
/// not being clever about.
fn emit_jump(o: &mut String, f: &crate::ir::Func, to: crate::ir::BlockId, args: &[Value]) {
    let target = f.block(to);
    debug_assert_eq!(
        target.params.len(),
        args.len(),
        "block argument arity mismatch"
    );
    if args.is_empty() {
        writeln!(o, "    goto b{};", to.0).unwrap();
        return;
    }
    writeln!(o, "    {{").unwrap();
    for (n, a) in args.iter().enumerate() {
        let t = f.ty_of(*a);
        let name = t.c_name();
        let sep = if name.ends_with('*') { "" } else { " " };
        writeln!(o, "        {name}{sep}tmp{n} = {a};").unwrap();
    }
    for (n, p) in target.params.iter().enumerate() {
        writeln!(o, "        {p} = tmp{n};").unwrap();
    }
    writeln!(o, "        goto b{};", to.0).unwrap();
    writeln!(o, "    }}").unwrap();
}

fn emit_term(o: &mut String, f: &crate::ir::Func, t: &Term) {
    match t {
        Term::Jump { to, args } => emit_jump(o, f, *to, args),
        Term::Brif {
            cond,
            then,
            then_args,
            els,
            els_args,
        } => {
            writeln!(o, "    if ({cond}) {{").unwrap();
            emit_jump(o, f, *then, then_args);
            writeln!(o, "    }} else {{").unwrap();
            emit_jump(o, f, *els, els_args);
            writeln!(o, "    }}").unwrap();
        }
        Term::Ret { val: Some(v) } => writeln!(o, "    return {v};").unwrap(),
        Term::Ret { val: None } => writeln!(o, "    return;").unwrap(),
    }
}

/// Render bytes as a C string literal. Escapes conservatively: anything
/// outside printable ASCII becomes an octal escape, which avoids both
/// encoding assumptions and the `\x` ambiguity where a following hex digit
/// would extend the escape.
fn c_string_literal(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() + 2);
    s.push('"');
    for &b in bytes {
        match b {
            b'"' => s.push_str("\\\""),
            b'\\' => s.push_str("\\\\"),
            b'\n' => s.push_str("\\n"),
            b'\t' => s.push_str("\\t"),
            b'\r' => s.push_str("\\r"),
            // A `?` is escaped so `??x` can never appear in the emitted
            // literal. `??!` and friends are trigraphs: C99 replaces them,
            // and both gcc and clang warn under -Wall that they are ignoring
            // one -- which the warning gate reads as a failure. `\?` is the
            // same character and cannot start a trigraph.
            b'?' => s.push_str("\\?"),
            0x20..=0x7e => s.push(b as char),
            other => {
                write!(s, "\\{:03o}", other).unwrap();
            }
        }
    }
    s.push('"');
    s
}

impl ArithOp {
    #[allow(dead_code)]
    fn is_checked(self) -> bool {
        true
    }
}
